### ISSUE TITLE
Coherence_assent in production

### ISSUE THREAD

**Issue by dielume** [danschultzer/coherence_assent#13]
Hello danschultzer, 
it is posible to use Coherence_assent in production? how can i change the callback method? 
for example , i want to use https://blizu.org/auth/google/callback in replace of localhost:8080/auth/google/callback
Thanks

**Comment by danschultzer** [comment]
Yeah, I'm using it in production. It should work out of the box if your app is running on https://blizu.org/.

**Comment by danschultzer** [comment]
Realized that you maybe haven't configured the endpoint:

```elixir
config :my_app, MyApp.Endpoint,
  # ...
  url: [scheme: "https", host: "blizu.org", port: 443]
```

**Comment by dielume** [comment]
Sorry you are right i must change url and port in prod.ex .
I am deploying with distillery and edeliver, [https://hexdocs.pm/distillery/use-with-phoenix.html#configuring-your-release](url), according that, url and port must be the same for issues in the websockets. However, everything seems to work well with some changes in nginx:
[https://github.com/phoenixframework/phoenix/issues/663](url) and the config: 
```
http: [port: {:system, "PORT"}],
url: [host: "blizu.org", port: 80],
```
Thanks for all your help
