### ISSUE TITLE
Support for UUID

### ISSUE THREAD

**Issue by danschultzer** [danschultzer/coherence_assent#14]
There needs to be support for users with `:binary_id` type primary key. I will look at this when I've got some more time.

**Comment by jung-hunsoo** [comment]
I think the coherence users with UUID pk will also has `id` field. Then it'd be enough to make association with `user_identities.id` and `user.id`.

Or `mix coherence_assent.install` can recognize pk of `users` table, then write a migration file accordingly.

**Comment by danschultzer** [comment]
I've previously implemented UUID in https://github.com/danschultzer/ex_oauth2_provider/pull/21 https://github.com/danschultzer/ex_oauth2_provider/pull/24. The `id` field will still be there, just as a string type instead. Both the schema belongs to, and the mix task has to be updated so the `user_id` column can be handled with the correct type.

**Comment by danschultzer** [comment]
I've moved on to [Pow](https://github.com/danschultzer/pow), that is a much cleaner user management system. There's UUID support in [PowAssent](https://github.com/danschultzer/pow_assent) by default due to this, so I won't continue this work on CoherenceAssent.
