### ISSUE TITLE
Regular email login not working 

### ISSUE THREAD

**Issue by AlmogRnD** [danschultzer/coherence_assent#15]
I added coherence_assent to my app, which already had coherence installed the installation went fine and everything is showing up, however now when I try to login with an email and password after I click the submit button the page refresh but does not redirect to my admin page, when I try to go to the admin page which is protected I'm taking back to the login (http://localhost:4000/sessions/new). 

I am seeing the URL bar the following after clicking the login button 

http://localhost:4000/sessions/new?_csrf_token=OxMjLkxBUx4eOA8BVwV0LFxxDx0xNgAAn%2BEmgjej%2Fpe5oCEu37Ijpw%3D%3D&_utf8=%E2%9C%93&session%5Bemail%5D=admin%40example.org&session%5Bpassword%5D=password

**Comment by danschultzer** [comment]
Hmm, not sure what goes wrong here. The routes setup from #16 looks fine. Are you using `coherence v0.5.0` and `phoenix 1.3`?

**Comment by AlmogRnD** [comment]
Using 

```
{:phoenix, "~> 1.3.2"},
{:coherence, "~> 0.5"},
{:coherence_assent, "~> 0.3.1"}
```

**Comment by danschultzer** [comment]
Thanks, I have a demo app with the same setup and it works. I think this is related to #16, as the missing `user_identities` table may cause a changeset error (`coherence` updates the user each time there's a login).

**Comment by danschultzer** [comment]
I think this is caused by the form not using a `POST` method, and I don't think this is caused by `coherence_assent`. But I don't know how it's possible in the first place as `http://localhost:4000/sessions/new` is a `POST` route and shouldn't be accessible as a `GET` request.

**Comment by danschultzer** [comment]
If the form is set with `<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f  -> %>` it should be working.

**Comment by AlmogRnD** [comment]
Fixed, an issue on my end I had an HTML <form> tag and then

`<%= form_for @conn, session_path(@conn, :create), [as: :session], fn f -> %> `

Just need to remove the form tag
