### ISSUE TITLE
ERROR 42P01 (undefined_table): relation "user_identities" does not exist

### ISSUE THREAD

**Issue by AlmogRnD** [danschultzer/coherence_assent#16]
Installed the page and now when I try to use GitHub login or to create an account I'm getting the following error  

Postgrex.Error at GET /auth/github/callback
ERROR 42P01 (undefined_table): relation "user_identities" does not exist

**Comment by AlmogRnD** [comment]
Here is my router 

```
defmodule MagnifyWeb.Router do
  use MagnifyWeb, :router
  use Coherence.Router
  use CoherenceAssent.Router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session
  end

  pipeline :protected do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
    plug Coherence.Authentication.Session, protected: true
  end

  pipeline :admin_layout do
    plug :put_layout, {MagnifyWeb.LayoutView, :admin}
  end

  scope "/" do
    pipe_through :browser
    coherence_routes()
    coherence_assent_routes()
  end

  scope "/" do
    pipe_through :protected
    coherence_routes :protected
  end

  scope "/", MagnifyWeb do
    pipe_through :browser # Use the default browser stack
    get "/", HomeController, :index
    get "/about", AboutController, :index
  end

  scope "/", MagnifyWeb do
    pipe_through [:protected, :admin_layout]
    # add protected resources below
    resources "/dashboard", DashboardController
    resources "/magnets", MagnetController
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

end

```

**Comment by danschultzer** [comment]
Did you run `mix coherence_assent.install`? There needs to be a migration file called `create_user_identities_tables`, and [you've to run `mix ecto.setup`](https://github.com/danschultzer/coherence_assent#getting-started).

**Comment by AlmogRnD** [comment]
So yes I ran mix coherence_assent.install  not sure about mix ecto.setup I just tried that and I'm getting the following error The database for Magnify.Repo has already been created

**Comment by danschultzer** [comment]
Try run `mix ecto.migrate`

**Comment by AlmogRnD** [comment]
I also just tried running mix ecto.migrate which ran but I got the following error 

```
mix ecto.migrate                                                                               
[info] == Running Magnify.Repo.Migrations.CreateCoherenceUser.change/0 forward
[info] create table users
** (Postgrex.Error) ERROR 42P07 (duplicate_table): relation "users" already exists
    (ecto) lib/ecto/adapters/sql.ex:200: Ecto.Adapters.SQL.query!/5
    (ecto) lib/ecto/adapters/postgres.ex:96: anonymous fn/4 in Ecto.Adapters.Postgres.execute_ddl/3
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/adapters/postgres.ex:96: Ecto.Adapters.Postgres.execute_ddl/3
    (ecto) lib/ecto/migration/runner.ex:104: anonymous fn/2 in Ecto.Migration.Runner.flush/0
    (elixir) lib/enum.ex:1899: Enum."-reduce/3-lists^foldl/2-0-"/3
    (ecto) lib/ecto/migration/runner.ex:102: Ecto.Migration.Runner.flush/0
    (stdlib) timer.erl:181: :timer.tc/2
    (ecto) lib/ecto/migration/runner.ex:26: Ecto.Migration.Runner.run/6
    (ecto) lib/ecto/migrator.ex:128: Ecto.Migrator.attempt/6
    (ecto) lib/ecto/migrator.ex:73: anonymous fn/4 in Ecto.Migrator.do_up/4
    (ecto) lib/ecto/adapters/sql.ex:576: anonymous fn/3 in Ecto.Adapters.SQL.do_transaction/3
    (db_connection) lib/db_connection.ex:1283: DBConnection.transaction_run/4
    (db_connection) lib/db_connection.ex:1207: DBConnection.run_begin/3
    (db_connection) lib/db_connection.ex:798: DBConnection.transaction/3
    (ecto) lib/ecto/migrator.ex:261: anonymous fn/4 in Ecto.Migrator.migrate/4
    (elixir) lib/enum.ex:1294: Enum."-map/2-lists^map/1-0-"/2
    (ecto) lib/mix/tasks/ecto.migrate.ex:83: anonymous fn/4 in Mix.Tasks.Ecto.Migrate.run/2
    (elixir) lib/enum.ex:737: Enum."-each/2-lists^foreach/1-0-"/2
    (elixir) lib/enum.ex:737: Enum.each/2
```

**Comment by danschultzer** [comment]
Oh, for some reason, there're two migrations that create the `user` table. It probably never gets to the `coherence_assent` migration file for this reason. Check `priv/repo/migrations` if a second user migration file has been added.

**Comment by AlmogRnD** [comment]
Ok their was duplicate files I deleted attached screenshot what I have now 
<img width="422" alt="screen shot 2018-04-20 at 9 14 18 pm" src="https://user-images.githubusercontent.com/169507/39080293-e240097a-44df-11e8-9494-70e50f6f19ed.png">

ran mix ecto.migrate again but still get the following error 

create table users
** (Postgrex.Error) ERROR 42P07 (duplicate_table): relation "users" already exists

**Comment by AlmogRnD** [comment]
So I just did 
mix ecto.drop 
The database for Magnify.Repo has been dropped

Than

mix ecto.setup 
The database for Magnify.Repo has been created

Which is fine, tried to login via github and got the following 

CoherenceAssent.CallbackCSRFError at GET /auth/github/callback
CSRF detected

```
 |> Coherence.current_user()
    |> Callback.handler(provider, user)
    |> Controller.callback_response(conn, provider, user, params)
  end
  defp callback_handler({:error, %{error: error}}, _provider, _params),
    do: raise error
  def get_config!(provider) do
    config = provider |> CoherenceAssent.config()
    config 
```

I have the config setup 

```
# %% coherence_assent Configuration %%
config :coherence_assent, :providers,
       [
         github: [
           client_id: "xxxx",
           client_secret: "xxx",
           strategy: CoherenceAssent.Strategy.Github
         ],
         google: [
           client_id: "xxxx",
           client_secret: "xxxxx",
           strategy: CoherenceAssent.Strategy.Google
         ]
       ]
# %% End coherence_assent Configuration %%
```

Did I miss a step?

**Comment by danschultzer** [comment]
This happens when the `state` argument is different from the `state` value in the session. I would try it again just to be sure that it the `state` wasn't changed for some reason during the first authorization (could happen if the `authorize_url` was reloaded in the browser).

**Comment by AlmogRnD** [comment]
@danschultzer yea I tried it again still getting the CSRF detected there is defiantly an issue

**Comment by AlmogRnD** [comment]
Attached gif showing the issues 

![issue](https://user-images.githubusercontent.com/169507/39088152-dc6a7d46-4561-11e8-89b9-a50748625a9a.gif)

**Comment by danschultzer** [comment]
Thanks. I'll test with my demo app to see if I can figure out what causes the issue.

**Comment by danschultzer** [comment]
For some reason, it seems like the session is not persistent. Can you check your endpoint module what options are set for `Plug.Session`. In my sample app I got this:

```elixir
  plug Plug.Session,
    store: :cookie,
    key: "_coherence_assent_demo_key",
    signing_salt: "Hu3DL3o4"
```

**Comment by danschultzer** [comment]
You can leave out the `signing_salt` if you post the options you have.

**Comment by AlmogRnD** [comment]
I have the following 

```
plug Plug.Session,
    store: :cookie,
    key: "_magnify_key",
    signing_salt: "xxxxx"
```

**Comment by danschultzer** [comment]
What dependencies do you've in `mix.exs`?

**Comment by AlmogRnD** [comment]
```
defp deps do
    [
      {:phoenix, "~> 1.3.2"},
      {:phoenix_pubsub, "~> 1.0"},
      {:phoenix_ecto, "~> 3.2"},
      {:postgrex, ">= 0.0.0"},
      {:phoenix_html, "~> 2.10"},
      {:phoenix_live_reload, "~> 1.0", only: :dev},
      {:gettext, "~> 0.15"},
      {:cowboy, "~> 1.0"},
      {:coherence, "~> 0.5"},
      {:coherence_assent, "~> 0.3.1"}
    ]
  end
```

And I will also have ExAdmin

**Comment by danschultzer** [comment]
Oh wait, I see it now, try visit `http://localhost:4000` instead. Pretty sure it sets the cookie on `0.0.0.0` domain, but you get redirected back to `localhost`.

**Comment by AlmogRnD** [comment]
So what should I be doing? Not sure I understood?

**Comment by AlmogRnD** [comment]
Ok got it, an issue on my end in my header template for the login buttons I have the following for the URL  href="/sessions/new" that is incorrect and what was causing the incorrect redirect to 0000. 

Yes, it works fine with localhost, closing thanks for the great support. I need to figure out the correct way to set URLs in Phonix

**Comment by danschultzer** [comment]
Cool! The host is set in the endpoint module, and looks like this:

```elixir
config :coherence_assent_demo, CoherenceAssentDemoWeb.Endpoint,
  url: [host: "localhost"]
```

**Comment by AlmogRnD** [comment]
Do I need to change that once I upload the app to hosting and correct domain?

**Comment by AlmogRnD** [comment]
@danschultzer quick question you might be able to help with this when I run "mix phx.server" 

I get the following "Running MagnifyWeb.Endpoint with Cowboy using http://0.0.0.0:4000"

Which created this issue, how do I set it to localhost 

I have this dev config 

```
config :magnify, MagnifyWeb.Endpoint,
  http: [port: 4000],
  debug_errors: true,
  code_reloader: true,
  check_origin: false,
  watchers: [node: ["node_modules/brunch/bin/brunch", "watch", "--stdin",
                    cd: Path.expand("../assets", __DIR__)]]
```

and my config 

# Configures the endpoint
```
config :magnify, MagnifyWeb.Endpoint,
  url: [host: "localhost"],
  secret_key_base: "xxxx",
  render_errors: [view: MagnifyWeb.ErrorView, accepts: ~w(html json)],
  pubsub: [name: Magnify.PubSub,
           adapter: Phoenix.PubSub.PG2]
```

**Comment by danschultzer** [comment]
You could maybe the config in dev to this:

```elixir
config :magnify, MagnifyWeb.Endpoint,
  http: [host: "localhost", port: 4000],
  # ...
```

**Comment by AlmogRnD** [comment]
Yea I tried that at first got a 

Could not start application magnify: Magnify.Application.start(:normal, []) returned an error: shutdown: failed to start child: MagnifyWeb.Endpoint

Not really clear where this is set within the framework

**Comment by danschultzer** [comment]
Oh, yeah, it has to be `url: [host: "localhost"]` but that's what it defaults to anyway: https://hexdocs.pm/phoenix/Phoenix.Endpoint.html

So I'm not sure if you can change it.

**Comment by AlmogRnD** [comment]
Thanks I think it's just an issue with the terminal output, localhost works fine
