### ISSUE TITLE
How to set redirect 

### ISSUE THREAD

**Issue by AlmogRnD** [danschultzer/coherence_assent#18]
After user logs in or creates their account using Github how can I set the redirect URL to a specific page? Right now it goes back to my home page which is my public site not the user admin or dashboard

**Comment by danschultzer** [comment]
You should use [the `redirects.ex` file](https://github.com/smpallen99/coherence/blob/master/priv/templates/coh.install/controllers/coherence/redirects.ex) that coherence creates. [`registration_create`](https://github.com/danschultzer/coherence_assent/blob/master/lib/coherence_assent/web/controllers/controller.ex#L12) and [`session_create`](https://github.com/danschultzer/coherence_assent/blob/master/lib/coherence_assent/web/controllers/controller.ex#L17) are used in `coherence_assent`.

**Comment by AlmogRnD** [comment]
Thanks that was it
