### ISSUE TITLE
Coherence 0.5.1 and upward changed module Coherence.Web to CoherenceWeb.

### ISSUE THREAD

**Issue by jung-hunsoo** [danschultzer/coherence_assent#20]
https://github.com/danschultzer/coherence_assent/blob/96379fe10e2018a29d0ca68812c995008d03cb4a/lib/coherence_assent/web/controllers/registration_controller.ex#L3

When I just updated Coherence to 0.5.2 from 0.5.0, a compile error occurred at L3 in RegistrationController, AuthController, and Controller.

That's because since Coherence 0.5.1 uses module CoherenceWeb instead of Coherence.Web. [v0.5.1](https://github.com/smpallen99/coherence/blob/v0.5.1/lib/coherence/web.ex) After changed them, there's no more compile error at least. (But I didn't tested all.)

Since it's more than a year that v0.5.1 was released, `coherence_assent` could consider followed up the breaking changes.

**Comment by danschultzer** [comment]
Wow, it’s incredible that they would release breaking changes like this as a minor update. Thanks for letting me know and for your PR! I’ll go through it in a few hours when I’m at my desk, and get a release out today.

It should be released as `v0.4.0`, and a `v0.3.2` should be release that limits coherence to its 0.5.0 release.

Also moving unrelated changes to its own PR would be helpful (the reactoring and removal or warnings you worked on).

Thanks again.

**Comment by jung-hunsoo** [comment]
@danschultzer I think because the Coherence is under active development with v0.x. It'll be a bit painful before v1.0 is released.

And for versioning rule, since `coherence_assent` is closely dependent to `coherence`, it'd be better to align with the same versions of `coherence`.

**Comment by danschultzer** [comment]
Yeah, I do agree on the principle. In this case I think it's better to wait for the full `v1.0.0` release before adhering closely to the same version though 🙂

**Comment by danschultzer** [comment]
FYI `v0.3.2` is released that freezes coherence to `v0.5.0`.

**Comment by jung-hunsoo** [comment]
@danschultzer This is great and clean release.

**Comment by danschultzer** [comment]
`v0.4.0` released with support for coherence `0.5.2` and up.

So, I've moved away from Coherence in favor of [Pow](https://github.com/danschultzer/pow), and I'm working on  [PowAssent](https://github.com/danschultzer/pow_assent) for Pow multi-provider support. It has much cleaner code, and more providers. Pow is a move towards a cleaner, more modular, and more elixir friendly user management solution.

You're probably good with Coherence currently, but in case you're interested, I wrote a guide on how to [switch from Coherence](https://github.com/danschultzer/pow/blob/master/guides/COHERENCE_MIGRATION.md). Hopefully I can release the full `v1.0.0` version of Pow later this month 😄

**Comment by jung-hunsoo** [comment]
Right, Coherence is a great library. And I looked over `Pow` some hours ago and found that it has modular and extensible structure whereas some features are immature; e.g. umbrella support, multiple schemas (ex. users, admins).

I'm going to take it a try in my hobby project today.
