### ISSUE TITLE
Cannot use with custom User module, install task uses hardcoded "coherence/user.ex" module

### ISSUE THREAD

**Issue by pradosh987** [danschultzer/coherence_assent#25]
Install task is using hard coded user file which is set to `coherence/user.ex`. Using with custom modal like `App.Account.User` throws `** (Mix) Cannot find Coherence user model at lib/firefly/coherence/user.ex` error

Code in `coherence_assent.install,ex`
```
defp update_user_model(config) do
    user_path = lib_path("coherence/user.ex")
    case File.lstat(user_path) do
      {:ok, %{type: :regular}} -> update_user_model_file(user_path)
                                  config
      _ -> Mix.raise "Cannot find Coherence user model at #{user_path}"
    end
  end
```

Solution:
Generate file path from Coherence.Config.user_schema, Coherence itself does same in `coh.install`.

**Comment by pradosh987** [comment]
Is coherence assent even compatible with custom user modules???

**Comment by danschultzer** [comment]
Yeah, you can use custom user module. CoherenceAssent pulls [the user module with `Coherence.Config.user_schema`](https://github.com/danschultzer/coherence_assent/blob/master/lib/coherence_assent/user_identities/user_identity.ex#L9). Your solution is the right way to fix this, any PR is most welcome!
