### ISSUE TITLE
OAuth registration fails on missing password field

### ISSUE THREAD

**Issue by jonathanraes** [danschultzer/coherence_assent#26]
Hi,

I'm having a problem with the oauth registration, a new user is inserted using the :registration changeset, which calls `validate_coherence(params)`. I believe this causes the changeset to become invalid as it requires the password param to be supplied. 

I fixed this by having coherence_assent use another changeset that skips the `validate_coherence` call, after which everything seems to be working correctly. Not sure if this is the right way to fix this though.

Can someone share their thoughts on this issue?

**Comment by danschultzer** [comment]
Isn't this working if you use `validate_coherence_assent` instead? Like this example:

```elixir
        def changeset(model, params \\ %{}) do
          model
          |> cast(params, @required_fields, @optional_fields)
          |> unique_constraint(:email)
          |> validate_coherence_assent(params)
        end
```

The install mix task should take care of this by renaming `validate_coherence` to `validate_coherence_assent`. `validate_coherence_assent` will only call `validate_coherence` if a password has been set.

**Comment by jonathanraes** [comment]
The install task only inserted the `validate_coherence_assent` call in my default changeset so I added it manually to the registration changeset. I didn't realise that `validate_coherence_assent` would call `validate_coherence` do I didn't remove the `validate_coherence` call.
Removing it fixed my issue, thanks for your help and quick reply!
